[package]
name = "redis-hyperminhash"
version = "0.1.0"
authors = ["ocadaruma <ocadaruma@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "0.2.62"

[build-dependencies]
cc = "1.0.45"
